# Generated by Django 3.0.5 on 2020-05-08 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='++', max_length=2)),
                ('deliverable', models.BooleanField(default=False)),
                ('product', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sellable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='$$', max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('returnable', models.BooleanField(default=False)),
                ('value', models.FloatField(default=1.0)),
                ('visual', models.CharField(default='', max_length=150)),
                ('sellid', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sellable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emporio.Sellable')),
                ('category', models.IntegerField(default=1)),
                ('description', models.TextField()),
            ],
            bases=('emporio.sellable',),
        ),
        migrations.CreateModel(
            name='SpreadBasket',
            fields=[
                ('basket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emporio.Basket')),
            ],
            bases=('emporio.basket',),
        ),
    ]
